# Módulo de Programação Python

# Trilha Python - Aula 7: Utilizando NumPy - Avançado

<img align="center" style="padding-right:10px;" src="Figuras/aula-12_fig_01.png">

__Objetivo__:  Trabalhar com pacotes e módulos disponíveis em python: __Numpy__. Aprender a trabalhar de forma eficiente com __NumPy__ arrays utilizando as funções universais (_ufunc_) e outros recursos avançados.

## Calculando com _ndarrays_

Como já foi discutido antes, a __NumPy__ é muito utilizada, não apenas pelas características dos objetos de tipo _ndarray_, nela implementados. O conjunto de operações e funções para trabalhar com os _ndarray_ são um importante diferencial. 

Operações com arrays envolvem, na maior parte das linguagens de programação, a utilização de laços ou estruturas de repetição para percorrer os elementos dos mesmos. 

A implementação de operações vetoriais, disponíveis para o processamento de _ndarrays_ na __NumPy__, representam um diferencial importante na hora de processar estruturas de grande porte. 

Na aula anterior tentamos utilizar _ndarrays_ para implementar multiplicação de matrizes e o resultado não foi muito promisor. 

Vejamos outro exemplo para entender melhor a questão.

In [1]:
import numpy as np
from random import uniform

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


Vamos criar uma lista muito grande com valores aleatórios entre 1 e 100. Utilizaremos o módulo ``uniform`` do pacote ``random``.  

In [2]:
lista = [uniform(1, 100) for _ in range(1000000)]
print(lista[:3], " ...", lista[-3:])
print("len(lista) =", len(lista))

[30.204336659912087, 69.93043321780024, 65.67417712941352]  ... [40.175592611014565, 76.69854823317009, 20.70558442887602]
len(lista) = 1000000


Agora vamos testar o custo computacional de calcular o inverso de cada um dos valores das listas. 

In [3]:
lista_inv = [1/x for x in lista]
print(lista_inv[:3], " ...", lista_inv[-3:])

%timeit lista_inv = [1/x for x in lista]


[0.033107828563148804, 0.014299925711677958, 0.015226684881478774]  ... [0.024890734274466916, 0.013038056430480473, 0.048296149448715846]
49.2 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Podemos fazer o mesmo experimento utilizando _ndarrays_.  

In [4]:
#array = np.random.uniform(1,100,1000000)
array = np.array(lista)
print(array[:3], " ...", array[-3:])
print("len(array) =", len(array))

[30.20433666 69.93043322 65.67417713]  ... [40.17559261 76.69854823 20.70558443]
len(array) = 1000000


In [5]:
def inv(x):
    y = np.empty_like(x)
    for i in range(len(x)):
        y[i] = 1/x[i]
    return y

array_inv = inv(array)

print(array_inv[:3], " ...", array_inv[-3:])

%timeit array_inv = inv(array)

[0.03310783 0.01429993 0.01522668]  ... [0.02489073 0.01303806 0.04829615]
216 ms ± 4.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Vejam que o desempenho com _ndarrays_ é pior que com listas. Este não era o resultado esperado. 

Entretanto, __NumPy__ disponibiliza uma interface apropriada que permite introduzir operações vetoriais, o que acelera significativamente o processamento de _ndarrays_ de grande porte. Compare o resultado anterior com o do exemplo a seguir.

In [6]:
#array = np.random.uniform(1,100,1000000)
array = np.array(lista)
print(array[:3], " ...", array[-3:])

array_inv = 1.0/array
print(array_inv[:3], " ...", array_inv[-3:])

%timeit array_inv = (1.0/array)

[30.20433666 69.93043322 65.67417713]  ... [40.17559261 76.69854823 20.70558443]
[0.03310783 0.01429993 0.01522668]  ... [0.02489073 0.01303806 0.04829615]
414 µs ± 73.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


As operações vetoriais são implementadas em __NumPy__ através das chamadas _ufuncs_. As _ufuncs_ são eficientes e flexíveis, permitindo realizar, de forma rápida, operações entre escalares e arrays, assim como operações entre arrays. 

Realizar os cálculos utilizando _ufuncs_ é sempre mais eficiente a implementação do mesmo cálculo utilizando estruturas de repetição. Veja os operadores aritméticos implementados em __NumPy__ através de _ufuncs_ nos exemplos a seguir.

| Operador	    | _ufunc_ equivalente | Descrição                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Adição de dois arrays ou de um array com um escalar         |
|``-``          |``np.subtract``      |Substração de dois arrays ou de um array com um escalar      |
|``-``          |``np.negative``      |Negativo unário           |
|``*``          |``np.multiply``      |Multiplicação de dois arrays ou de um array por um escalar   |
|``/``          |``np.divide``        |Divisão de dois arrays ou de um array por um escalar       |
|``//``         |``np.floor_divide``  |Divisão truncada de dois arrays ou de um array por um escalar  |
|``**``         |``np.power``         |Exponenciação  |
|``%``          |``np.mod``           |Resto da divisão |

In [8]:
# Adição de arrays
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

# este operador adição é implementado como uma _ufunc_ (função universal) ``np.add``
print(np.add(x,y))
print("________________")
# Adição de array e escalar
z = x + 10
print(z)
print(np.add(x,10))

[5 7 9]
[5 7 9]
________________
[11 12 13]
[11 12 13]


In [9]:
# substração de arrays
z = x - y
print(z)

# este operador substração é implementado como uma _ufunc_ (função universal) ``np.subtract``
print(np.subtract(x,y))
print("________________")
# substração de array e escalar
z = x - 10
print(z)
print(np.subtract(x,10))

[-3 -3 -3]
[-3 -3 -3]
________________
[-9 -8 -7]
[-9 -8 -7]


In [10]:
# negativo
z = -z
print(z)

# este operador negativo é implementado como uma _ufunc_ (função universal) ``np.negative``
print(np.negative(z))

[9 8 7]
[-9 -8 -7]


In [11]:
# multiplicação de arrays
z = x * y
print(z)

# este operador multiplicação é implementado como uma _ufunc_ (função universal) ``np.multiply``
print(np.multiply(x,y))
print("________________")
# multiplicação de array e escalar
z = 2 * x
print(z)
print(np.multiply(2,x))

[ 4 10 18]
[ 4 10 18]
________________
[2 4 6]
[2 4 6]


In [12]:
# divisão de arrays
z = x / y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.divide``
print(np.divide(x,y))
print("________________")
# divisão de array e escalar
z = x / 2
print(z)
print(np.divide(x,2))


[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
________________
[0.5 1.  1.5]
[0.5 1.  1.5]


In [13]:
# divisão truncada de arrays
z = x // y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.divide``
print(np.floor_divide(x,y))
print("________________")
# divisão truncada de array e escalar
z = x // 2
print(z)
print(np.floor_divide(x,2))

[0 0 0]
[0 0 0]
________________
[0 1 1]
[0 1 1]


In [14]:
# exponenciação de arrays
z = x ** y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.power``
print(np.power(x,y))
print("________________")
# exponenciação de array e escalar
z = x ** 2
print(z)
print(np.power(x,2))

[  1  32 729]
[  1  32 729]
________________
[1 4 9]
[1 4 9]


In [15]:
# resto da divisão de arrays
z = x % y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.mod``
print(np.mod(x,y))
print("________________")
# resto da divisão de array e escalar
z = x % 2
print(z)
print(np.mod(x,2))

[1 2 3]
[1 2 3]
________________
[1 0 1]
[1 0 1]


Além deste conjunto básico de operadores, implementados na furma de _unfunc_ que sobrecarregam os operadores aritméticos tradicionais, __NumPy__ disponibiliza um conjunto adicional de funções:

|Nome da Função     |   Descrição                                   |
|:-------------------:|-----------------------------------------------|
| ``np.abs``<br>ou<br>``np.absolute``| Retorna o valor absoluto dos elementos do<br>_ndarray_. Também funciona com _ndarrays_ de<br>números complexos.     |

In [16]:
# valor absoluto 
x = np.array([-1.2,2.3,-3.4])
z = np.abs(x)
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.absolute``
print(np.absolute(x))
#ou
print(np.abs(x))
# No caso de números complexos, o valor absoluto é a magnitude
x = np.array([-1+1j,2-2j,-3+3j])
z = np.abs(x)
print(z)


[1.2 2.3 3.4]
[1.2 2.3 3.4]
[1.2 2.3 3.4]
[1.41421356 2.82842712 4.24264069]


Funções Trigonométricas

|Nome da Função     |   Descrição                                     |
|:-------------------:|-----------------------------------------------|
| ``np.sin``          | Retorna o seno dos elementos do array         |
| ``np.cos``          | Retorna p cosseno dos elementos do array      |
| ``np.tan``          | Retorna a tangente dos elementos do array     |
| ``np.arcsin``       | Retorna o arco-seno dos elementos do array    |
| ``np.arccos``       | Retorna o arco-cosseno dos elementos do array |
| ``np.arctan``       | Retorna a arco-tangente dos elementos do array    |

In [17]:
ang = np.linspace(0,2*np.pi,25) # ângulos em radianos
#print(ang)
print(np.rad2deg(ang)) # ângulos em graus


[  0.  15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165. 180. 195.
 210. 225. 240. 255. 270. 285. 300. 315. 330. 345. 360.]


In [18]:
print("Seno: \n", np.sin(ang))
print("Cosseno: \n", np.cos(ang))
print("Tangente: \n", np.tan(ang))

Seno: 
 [ 0.00000000e+00  2.58819045e-01  5.00000000e-01  7.07106781e-01
  8.66025404e-01  9.65925826e-01  1.00000000e+00  9.65925826e-01
  8.66025404e-01  7.07106781e-01  5.00000000e-01  2.58819045e-01
  1.22464680e-16 -2.58819045e-01 -5.00000000e-01 -7.07106781e-01
 -8.66025404e-01 -9.65925826e-01 -1.00000000e+00 -9.65925826e-01
 -8.66025404e-01 -7.07106781e-01 -5.00000000e-01 -2.58819045e-01
 -2.44929360e-16]
Cosseno: 
 [ 1.00000000e+00  9.65925826e-01  8.66025404e-01  7.07106781e-01
  5.00000000e-01  2.58819045e-01  6.12323400e-17 -2.58819045e-01
 -5.00000000e-01 -7.07106781e-01 -8.66025404e-01 -9.65925826e-01
 -1.00000000e+00 -9.65925826e-01 -8.66025404e-01 -7.07106781e-01
 -5.00000000e-01 -2.58819045e-01 -1.83697020e-16  2.58819045e-01
  5.00000000e-01  7.07106781e-01  8.66025404e-01  9.65925826e-01
  1.00000000e+00]
Tangente: 
 [ 0.00000000e+00  2.67949192e-01  5.77350269e-01  1.00000000e+00
  1.73205081e+00  3.73205081e+00  1.63312394e+16 -3.73205081e+00
 -1.73205081e+00 -1.000

In [19]:
print("Arco seno: \n", np.rad2deg(np.arcsin(np.sin(ang))))
print("Arco cosseno: \n", np.rad2deg(np.arccos(np.cos(ang))))
print("Arco tangente: \n", np.rad2deg(np.arctan(np.tan(ang))))

Arco seno: 
 [ 0.00000000e+00  1.50000000e+01  3.00000000e+01  4.50000000e+01
  6.00000000e+01  7.50000000e+01  9.00000000e+01  7.50000000e+01
  6.00000000e+01  4.50000000e+01  3.00000000e+01  1.50000000e+01
  7.01670930e-15 -1.50000000e+01 -3.00000000e+01 -4.50000000e+01
 -6.00000000e+01 -7.50000000e+01 -9.00000000e+01 -7.50000000e+01
 -6.00000000e+01 -4.50000000e+01 -3.00000000e+01 -1.50000000e+01
 -1.40334186e-14]
Arco cosseno: 
 [  0.  15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165. 180. 165.
 150. 135. 120. 105.  90.  75.  60.  45.  30.  15.   0.]
Arco tangente: 
 [ 0.00000000e+00  1.50000000e+01  3.00000000e+01  4.50000000e+01
  6.00000000e+01  7.50000000e+01  9.00000000e+01 -7.50000000e+01
 -6.00000000e+01 -4.50000000e+01 -3.00000000e+01 -1.50000000e+01
 -7.01670930e-15  1.50000000e+01  3.00000000e+01  4.50000000e+01
  6.00000000e+01  7.50000000e+01  9.00000000e+01 -7.50000000e+01
 -6.00000000e+01 -4.50000000e+01 -3.00000000e+01 -1.50000000e+01
 -1.40334186e-14]


Funções exponenciais e logarítmicas

|Nome da Função     |   Descrição                                     |
|:-------------------:|-----------------------------------------------|
| ``np.exp``          | Retorna $e^x$         |
| ``np.exp2``         | Retorna $2^x$      |
| ``np.power``        | Retorna $a^x$     |
| ``np.ln``           | Retorna $\log_e x$ ou simplesmente $\ln x$    |
| ``np.log2``         | Retorna $\log_2 x$  |
| ``np.log10``        | Retorna $\log_{10} x$ |

In [20]:
x = np.array([1,2,3])
print("Exponencial (e**x): \n", np.exp(x))
print("Exponencial (2**x): \n", np.exp2(x))
print("Exponencial (10**x): \n", np.power(10,x))

Exponencial (e**x): 
 [ 2.71828183  7.3890561  20.08553692]
Exponencial (2**x): 
 [2. 4. 8.]
Exponencial (10**x): 
 [  10  100 1000]


In [21]:
print("Logaritmo natural: \n", np.log(np.exp(x)))
print("Logaritmo base 2: \n", np.log2(np.exp2(x)))
print("Logaritmo base 10: \n", np.log10(np.power(10,x)))

Logaritmo natural: 
 [1. 2. 3.]
Logaritmo base 2: 
 [1. 2. 3.]
Logaritmo base 10: 
 [1. 2. 3.]


In [22]:
#outros logaritmos
#log base 3 de x pode ser calculado como log(x)/log(3)
print("Logaritmo base 3: \n", np.log(np.power(3,x))/np.log(3))

Logaritmo base 3: 
 [1. 2. 3.]


As limitações impostas pela aritmética de ponto flutuante faz com que, em alguns casos, seja necessário utilizar artifícios matemáticos para melhorar a precisão dos resultados. Para estes casos a __NumPy__ disponibiliza funções especiais como a utilizada no seguinte exemplo. 

In [23]:
x = np.array([0, 0.001, 0.01, 0.1])
print("Exponencial (e**x): \n", np.exp(x))
print("Exponencial (e**x - 1): \n", np.expm1(x))
#print("Logaritmo natural: \n", np.log(x))
print("Logaritmo natural (1 + x): \n", np.log1p(x))

Exponencial (e**x): 
 [1.         1.0010005  1.01005017 1.10517092]
Exponencial (e**x - 1): 
 [0.         0.0010005  0.01005017 0.10517092]
Logaritmo natural (1 + x): 
 [0.         0.0009995  0.00995033 0.09531018]


Para valores do argumento muito pequenos estas funções conseguem retornar um resultado com maior precisão. 

MAs vamos retomar o exemplo do final da aula anterior 

Relembrando a definição de GEMM que implementa a seguinte operação

$C = \alpha AB + \beta C$ 

De forma que:

$C[i,j] = \alpha \sum_{k=0}^{k<l} {A[i,k] B[k,j]} + \beta C[i,j]$

Vamos primeiramente revisar a implementação baseada exclusivamente no uso de estruturas de repetição.

In [24]:
#Esta é uma implementação específica para ndarrays
def GEMM_loops(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    for i in range(mc):
        for j in range(nc):
            val = 0
            for k in range(la):
                val += A[i,k]*B[k,j]
            C[i,j] = alpha*val + beta*C[i,j]
    return C

In [25]:
# Dada uma matriz A de n linhas e l colunas
n = 256
l = 128
A = np.random.random((n,l))
#A = np.ones((n,l))
# Uma matriz B de l linhas e n colunas
m = 256
B = np.random.random((l,m))
#B= np.ones((l,m))
# Uma matriz C de n linhas e m colunas
#C = np.ones((n,m))
#C = np.zeros((n,m))
C = np.random.random((n,m))
# E os escalares alpha e beta
alpha = 0.5
#alpha = 1.0
beta = 1.5
#beta = 1.0
#print(A)
#print(B)
#print(C)

In [26]:
C1 = C.copy()
%timeit Z = GEMM_loops(alpha, A, B, beta, C1)
C1 = GEMM_loops(alpha, A, B, beta, C1)

2.69 s ± 19.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Podemos então tentar usar a _ufunc_ para melhorar o desempenho

In [27]:
def GEMM_ufunc1(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            val = 0
            for k in range(la):
                val += A[i,k]*B[k,j]
            C[i,j] += alpha*val

    return C

In [28]:
C2 = C.copy()
%timeit Z = GEMM_ufunc1(alpha, A, B, beta, C2)
C2= GEMM_ufunc1(alpha, A, B, beta, C2)

2.71 s ± 34.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
def GEMM_ufunc2(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            C_ = A[i,:] * B[:,j].T
            val = 0
            for k in range(la):
                val += C_[k]
            C[i,j] += alpha*val
    
    return C

In [30]:
C3 = C.copy()
%timeit Z = GEMM_ufunc2(alpha, A, B, beta, C3)
C3= GEMM_ufunc2(alpha, A, B, beta, C3)

1.23 s ± 8.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Queda significativa no tempo total de processamento. Podemos melhorar ainda mais?

Quando trabalhamos com uma grande quantidade de dados, muitas vezes se faz necessário começar par fazer uma análise estatística dos mesmos, 

Algumas métricas utilizadas em estatística, como as medidas de valor central ou as medidas de espalhamento, ou ainda medidas de correlação, podem ser um necessárias.

De forma geral a média e o desvio pdrão é bom ponto de partida. 

__NumPy__ disponibiliza funções de agregação integradas rápidas para trabalhar em _ndarrays_ que são muito relevantes, por exemplo, para este tipo de análises.

Podemos começar pelo algoritmo simples, que já foi utilizado anteriormente, para calcular a soma de um conjunto de elementos, por exemplo, para calcular a média do conjunto. 

Se os valores estão numa lista, podemos utilizar a função ``sum``

In [31]:
from random import random   
matSize = 512
vetX = [random() for i in range(matSize)]
soma = sum(vetX)
print(soma)

255.7764421459208


Podemos obter o mesmo resultado utilizando os recursos da __NumPy__, particularmente a função ``sum`` 

In [32]:
#import numpy as np
x = np.array(vetX)
soma = np.sum(x)
print(soma)

255.7764421459209


Vamos comparar o desempenho destas duas implementações.

In [34]:
matSize = 1000000
vetX = [random() for i in range(matSize)]
x = np.array(vetX)
%timeit sum(vetX)
%timeit np.sum(x)

3.73 ms ± 35.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
207 µs ± 3.86 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Repare que esta função pode ser utilizada na nossa implementação da para _ndarrays_ do __GEMM__.

In [36]:
def GEMM_ufunc3(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            C[i,j] += alpha*np.sum(A[i,:] * B[:,j].T)
    
    return C

In [37]:
C4 = C.copy()
%timeit Z = GEMM_ufunc3(alpha, A, B, beta, C4)
C4= GEMM_ufunc3(alpha, A, B, beta, C4)

292 ms ± 1.68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


No exercício da prova do módulo anterior utilizamos as funções ``min`` e ``max``, que também tem implementações muito eficientes na __NumPy__

In [38]:
print(max(vetX))
print(np.max(x))
%timeit max(vetX)
%timeit np.max(x)

0.9999999253427423
0.9999999253427423
11.1 ms ± 29.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
319 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [39]:
print(min(vetX))
print(np.min(x))
%timeit min(vetX)
%timeit np.min(x)

4.2970861580116093e-07
4.2970861580116093e-07
10.7 ms ± 46.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
318 µs ± 1.76 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Este tipo de funções são chamadas de funções agregadoras. Outras funções de agregação estão disponíveis. A maioria delas uma versão segura para __NaN__, que calcula o resultado ignorando os valores ausentes, que são marcados pelo valor __NaN__ de ponto flutuante. Algumas dessas funções seguras para NaN não foram adicionadas até o NumPy 1.8, portanto, não estarão disponíveis em versões mais antigas do NumPy. Veja a tabela a seguir.

|Função             |   Versão __NaN-__safe  | Descrição                                  |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Calcula a soma dos elementos                  |
| ``np.prod``       | ``np.nanprod``      | Calcula o produto dos elementos               |
| ``np.mean``       | ``np.nanmean``      | Calcula o valor médio                         |
| ``np.std``        | ``np.nanstd``       | Calcula o desvio padrão                       |
| ``np.var``        | ``np.nanvar``       | Calcula a variância                              |
| ``np.min``        | ``np.nanmin``       | Retorna o valor mínimo                            |
| ``np.max``        | ``np.nanmax``       | Retorna o valor máximo                            |
| ``np.argmin``     | ``np.nanargmin``    | Retorna o índice de valor mínimo                   |
| ``np.argmax``     | ``np.nanargmax``    | Retorna o índice de valor máximo                   |
| ``np.median``     | ``np.nanmedian``    | Calcula a mediana                    |
| ``np.percentile`` | ``np.nanpercentile``| Calcula os percentil      |
| ``np.any``        | N/A                 | Avalie se algum elemento é verdadeiro        |
| ``np.all``        | N/A                 | Avalie se todos os elementos são verdadeiros        |

Estas funções permitam trabalhar com arrays multidimensionais.

In [41]:
A = np.random.random((3,3))
print(A)
print("Soma: ", np.sum(A))
print("Máximo: ", np.max(A))
print("Índice do máximo: ", np.argmax(A))
print("Mínimo: ", np.min(A))
print("Índice do mínimo: ", np.argmin(A))
print("Média: ", np.mean(A))
print("Mediana: ", np.median(A))
print("Desvio padrão: ", np.std(A))


[[0.07848294 0.27831902 0.34138839]
 [0.51152062 0.31571995 0.81675993]
 [0.34907165 0.45089438 0.31167847]]
Soma:  3.4538353411643734
Máximo:  0.8167599329447964
Índice do máximo:  5
Mínimo:  0.07848294481490259
Índice do mínimo:  0
Média:  0.38375948235159707
Mediana:  0.34138838870458654
Desvio padrão:  0.19016205228013458


As funções de agregação pode receber também um argumento adicional que especifica o eixo ao longo do qual a agregação deve ser calculada. Por exemplo, podemos encontrar o valor máximo de cada coluna especificando ``axis=0``, e de cada linha especificando ``axis=1``

In [42]:
print(A)
print("Soma: ", np.sum(A, axis=0))
print("Máximo: ", np.max(A, axis=0))
print("Índice do máximo: ", np.argmax(A, axis=0))
print("Mínimo: ", np.min(A, axis=0))
print("Índice do mínimo: ", np.argmin(A, axis=0))
print("Média: ", np.mean(A, axis=0))
print("Mediana: ", np.median(A, axis=0))
print("Desvio padrão: ", np.std(A, axis=0))

[[0.07848294 0.27831902 0.34138839]
 [0.51152062 0.31571995 0.81675993]
 [0.34907165 0.45089438 0.31167847]]
Soma:  [0.93907521 1.04493334 1.46982679]
Máximo:  [0.51152062 0.45089438 0.81675993]
Índice do máximo:  [1 2 1]
Mínimo:  [0.07848294 0.27831902 0.31167847]
Índice do mínimo:  [0 0 2]
Média:  [0.31302507 0.34831111 0.48994226]
Mediana:  [0.34907165 0.31571995 0.34138839]
Desvio padrão:  [0.1786149  0.07412693 0.23141307]


Temos ainda a implementação dos produtos vetoriais e matrizais da álgebra linear. 

A função ``np.dot`` implementa o produto escalar de duas matrizes. 

* Se ``a`` e ``b`` são matrizes 1-D, o resultado é o produto interno de vetores (sem complexa conjugada).

* Se ``a`` e ``b`` forem matrizes 2-D, o resultado é uma multiplicação de matrizes, mas é preferível usar ``matmul`` ou ``a @ b``.

Se ``a`` ou ``b`` for escalar, é equivalente a multiplicar e usar ``numpy.multiply(a, b)`` ou ``a * b``.

In [43]:
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.dot(x,y)
print(z)

32


In [44]:
A = np.random.random((3,3))
B = np.random.random((3,3))

C = np.dot(A,B)
print(C)

[[0.63593096 0.26495285 0.38804623]
 [0.85325056 0.64093499 0.63159297]
 [0.73863102 0.52477214 0.68323269]]


Podemos retomar nossa implementação a GEMM para usar o produto escalar de vetores.

In [45]:
# Dada uma matriz A de n linhas e l colunas
n = 256
l = 128
A = np.random.random((n,l))
#A = np.ones((n,l))
# Uma matriz B de l linhas e n colunas
m = 256
B = np.random.random((l,m))
#B= np.ones((l,m))
# Uma matriz C de n linhas e m colunas
#C = np.ones((n,m))
#C = np.zeros((n,m))
C = np.random.random((n,m))
# E os escalares alpha e beta
alpha = 0.5
#alpha = 1.0
beta = 1.5
#beta = 1.0
#print(A)
#print(B)
#print(C)

In [46]:
def GEMM_ufunc4(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            C[i,j] += alpha*np.dot(A[i,:],B[:,j].T)
    
    return C

In [47]:
C5 = C.copy()
%timeit Z = GEMM_ufunc4(alpha, A, B, beta, C5)
C5= GEMM_ufunc4(alpha, A, B, beta, C4)

101 ms ± 561 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
%timeit Z = alpha*np.dot(A,B)+beta*C
print((alpha*np.dot(A,B)+beta*C).shape)

483 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
(256, 256)


In [49]:
%timeit Z = alpha*np.matmul(A,B) + beta*C
print((alpha*np.matmul(A,B) + beta*C).shape)

470 µs ± 36.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
(256, 256)


In [50]:
%timeit Z = alpha*A@B + beta*C
print((alpha*A@B + beta*C).shape)

487 µs ± 36 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
(256, 256)


In [51]:
# Dada uma matriz A de n linhas e l colunas
n = 1024
l = 1024
A = np.random.random((n,l))
#A = np.ones((n,l))
# Uma matriz B de l linhas e n colunas
m = 1024
B = np.random.random((l,m))
#B= np.ones((l,m))
# Uma matriz C de n linhas e m colunas
#C = np.ones((n,m))
#C = np.zeros((n,m))
C = np.random.random((n,m))
# E os escalares alpha e beta
alpha = 0.5
#alpha = 1.0
beta = 1.5
#beta = 1.0
#print(A)
#print(B)
#print(C)

In [52]:
%timeit Z = GEMM_ufunc4(alpha, A, B, beta, C)

7.98 s ± 94.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
gflop = (2.0*1024 + 2)*(1024**2)*1E-9
print(gflop/7.98)

0.26937102756892234


In [54]:
%timeit Z = alpha*np.dot(A,B)+beta*C

29 ms ± 854 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
print(gflop/(29*1E-3))

74.12347586206897


In [56]:
%timeit Z = alpha*np.matmul(A,B) + beta*C

28.2 ms ± 650 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [57]:
%timeit Z = alpha*A@B + beta*C

29.4 ms ± 690 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
