# Módulo de Programação Python

# Trilha Python - Aula 13: Utilizando NumPy - Avançado

<img align="center" style="padding-right:10px;" src="Figuras/aula-12_fig_01.png">

__Objetivo__:   Trabalhar com pacotes e módulos disponíveis em python: __Numpy__. Introduzir recursos avançados da __NumPy__ para trabalhar com tipos diferentes de dados, subconjuntos e operações aritméticas e lógicas.

## Broadcasting
Até aqui vimos como as _ufunc_ do __NumPy__ podem ser usadas para vetorizar operações e, assim, substituir o uso de estruturas de repetição lentas. 

Outro meio de vetorizar operações é usar a funcionalidade de broadcasting do __NumPy__. 

Broadcasting é simplesmente um conjunto de regras para aplicar _ufuncs_ binários (por exemplo, adição, subtração, multiplicação, etc.) em matrizes de tamanhos diferentes.

Já vimos que as _unfuncs_ binárias podem operar com facilidade e eficiência em _ndarrays_ do mesmo tamanho. 

Podemos reproduzir um dos exemplos da aula anterior.

In [1]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
# Adição de arrays
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

[5 7 9]


Também vimos que este tipo de operação pode ser utilizada para somar um escalar com um _ndarray_. 

In [3]:
# Adição de array e escalar
z = x + 10
print(z)

[11 12 13]


Podemos pensar este exemplo como uma operação que trata o escalar como um _ndarray_ do tipo ``[10, 10, 10]``, e adiciona com o outro operando, neste caso outro _ndarray_ do mesmo tamanho. 

A vantagem de utilizar broadcasting do __NumPy__  é que, de fato, o tal _ndarray_ com elementos repetidos não é criado, simplificando o procedimento e otimizando o uso de memória.

O mecanismo de broadcasting pode ser aplicado em para _ndarrays_ de dimensão superior.

In [9]:
A = np.array([[1,2,3],[4,5,6]])
print("A = \n", A)
print("A.shape = ", A.shape)
print("x = \n", x)
print("x.shape = ", x.shape)
B = A + x 
print("B = A + x = \n", B)

A = 
 [[1 2 3]
 [4 5 6]]
A.shape =  (2, 3)
x = 
 [1 2 3]
x.shape =  (3,)
B = A + x = 
 [[2 4 6]
 [5 7 9]]


Vejamos um exemplo mais complexo

In [10]:
#a = np.array([0, 1, 2])
a = np.arange(3)
#b = np.array([[0], [1], [2]])
b = np.arange(3).reshape((3,1))
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [11]:
print("a + b = \n", a + b)

a + b = 
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


Para entender melhor como o broadcasting funciona podemos colocar as operações em função de um conjunto  de regras que definem como acontece a interação entre as duas matrizes:

__Regra 1__: Se as duas matrizes diferirem no número de dimensões, a forma (_shape_) daquela com menos dimensões será preenchida com uns no lado esquerdo até igualar o número de dimensões das duas matrizes.



In [12]:
A = np.ones((2,3))
x = np.arange(3)

In [13]:
print("A.shape = ", A.shape)
print("x.shape = ", x.shape)

A.shape =  (2, 3)
x.shape =  (3,)


In [15]:
print("A = \n", A)
print("x = \n", x)

A = 
 [[1. 1. 1.]
 [1. 1. 1.]]
x = 
 [0 1 2]


No exemplo anterior o array ``x`` tem apenas uma dimensão enquanto a matriz ``A`` tem duas. Neste caso se adiciona uma dimensão à esquerda de ``x``, ou seja, se cria um array com uma linha e 3 colunas.  

__Regra 2__: Se a forma dos dois arrays não corresponder em alguma dimensão, o array que na sua forma (_shape_) tiver dimensão igual a 1, naquela dimensão, é esticado para corresponder à forma do outro array.

Veja no exemplo anterior que, após aplicar a __Regra 1__ o array ``x`` agora tem _shape_ ``(1,3)``, enquanto que a matriz ``A`` tem _shape_ ``(2,3)``. Neste caso o se cria mais uma linha em ``x``, repetindo a primeira para que os dois arrays fiquem do mesmo tamanho. O resultado será então.

In [14]:
print("A + x = \n", A + x)

A + x = 
 [[1. 2. 3.]
 [1. 2. 3.]]


Veja outro exemplo.

In [16]:
A = np.arange(3).reshape((3, 1))
x = np.arange(3)

In [17]:
print("A.shape = ", A.shape)
print("x.shape = ", x.shape)

A.shape =  (3, 1)
x.shape =  (3,)


Veja que neste caso, novamente as dimensões das matrizes não coincidem. Novamente se adiciona uma dimensão a ``x`` que pasa a ter _shape_ ``(1,3)``. Como a _shape_ de ``A`` é ``(3,1)``, se _esticam_ as colunas de ``x`` apara preencher as duas novas linhas e se se esticam as linhas de ``A`` para preencher duas novas colunas. Desta forma se opera com duas matrizes de ``(3,3)``.

In [18]:
print("A = \n", A)
print("x = \n", x)
print("A + x = \n", A + x)

A = 
 [[0]
 [1]
 [2]]
x = 
 [0 1 2]
A + x = 
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


__Regra 3__: Se em qualquer dimensão os tamanhos discordam e nenhum deles for igual a 1, um erro é lançado.

Ou seja:

In [19]:
A = np.ones((3, 2))
x = np.arange(3)

In [20]:
print("A.shape = ", A.shape)
print("x.shape = ", x.shape)

A.shape =  (3, 2)
x.shape =  (3,)


In [21]:
print("A = \n", A)
print("x = \n", x)
try:
    print("A + x = \n", A + x)
except ValueError as e:
    print("ValueError:", e)

A = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
x = 
 [0 1 2]
ValueError: operands could not be broadcast together with shapes (3,2) (3,) 


## Outras _unfuc_ : Operações de comparação.

__NumPy__ também implementa operadores de comparação como ``<`` (menor que) e ``>`` (maior que) elemento a elemento, como _ufuncs_ . O resultado desses operadores de comparação é sempre um array com tipo de dados _booleano_. Todas as seis operações de comparação padrão estão disponíveis:

| Operador	    | _ufunc_             |
|:---------------:|---------------------|
|``==``         |``np.equal``         |
|``<``          |``np.less``          |
|``>``          |``np.greater``       |
|``!=``         |``np.not_equal``     |
|``<=``         |``np.less_equal``    |
|``>=``         |``np.greater_equal`` |

Podemos então fazer a seguinte análise:
* Suponha que obtemos, de alguma fonte, as notas em cada uma das três avaliações de um curso, assim como a media final, de uma turma de alunos. 

In [22]:
# Vamos gerar as notas de forma aleatória para 30 alunos
notas = np.zeros((30, 4))
notas[:, :3] = np.round(np.random.uniform(4, 10, size=(30, 3)),1)
notas[:, 3] = np.round(np.mean(notas[:, :3], axis=1)) # axis=1 indica que a média deve ser calculada por linha



In [23]:
print(notas[:5, :])
print(" ... ")
print(notas[-5:, :])

[[8.8 9.2 7.2 8. ]
 [5.3 5.4 6.7 6. ]
 [9.4 7.8 8.1 8. ]
 [9.7 5.2 7.2 7. ]
 [9.6 4.9 8.1 8. ]]
 ... 
[[5.2 5.9 7.4 6. ]
 [7.9 9.6 6.3 8. ]
 [7.3 9.  7.7 8. ]
 [7.  8.9 4.7 7. ]
 [5.  5.9 9.1 7. ]]


Agora queremos saber quantos alunos tiveram nota maior ou igual a 7,0 na primeira avaliação.

In [24]:
aprov1raAva = notas[:,0] >= 7
print("aprov1raAva = \n", aprov1raAva)

aprov1raAva = 
 [ True False  True  True  True  True False False  True  True False False
  True False False  True  True False  True False  True False False False
 False False  True  True  True False]


In [27]:
nAprov = np.sum(aprov1raAva)
#ou
#nAprov = np.count_nonzero(aprov1raAva)
#ou
#nAprov = aprov1raAva.sum()
print(nAprov, "alunos foram aprovados na primeira avaliação")

15 alunos foram aprovados na primeira avaliação


Podemos identificar quantos alunos estão abaixo da média da turma na segunda avaliação. 

In [28]:
mean2daAval = np.mean(notas[:,1])
print("A média da segunda avaliação foi", mean2daAval)
nAbaiMedia = np.sum(notas[:,1] < mean2daAval)
print(nAbaiMedia, "alunos ficaram abaixo da média na segunda avaliação")

A média da segunda avaliação foi 7.739999999999999
12 alunos ficaram abaixo da média na segunda avaliação


Podemos identificar quantas notas, nas três avaliações, foram maiores que 9,0

In [29]:
notasMaiores = notas[:,:3] > 9
print(notasMaiores[:5, :])
print("...")
print(notasMaiores[-5:, :])


[[False  True False]
 [False False False]
 [ True False False]
 [ True False False]
 [ True False False]]
...
[[False False False]
 [False  True False]
 [False False False]
 [False False False]
 [False False  True]]


In [30]:
quantMaiores = np.sum(notasMaiores)
print(quantMaiores, "notas maiores que 9")

20 notas maiores que 9


Ainda podemos perguntar se tem alguma nota, na média final, menor que 5,0

In [31]:
np.any(notas[:, 3] < 5)

False

Ou se todas as notas da média final são menores que 9,0

In [32]:
np.all(notas[:, 3] < 9)

False

Ou se um aluno específico teve alguma nota abaixo de 6,0

In [34]:
np.any(notas[:, :3] < 5, axis=0)

array([ True,  True,  True])

## Operadores lógicos

Até aqui conseguimos contar a quantidade de alunos com nota menor ou maior ed um determinado valor. Os operadores relacionais entretanto podem ser utilizados, quando combinados com operadores lógicos, poara determinar, por exemplo, quantos alunos estão de prova final (media menor que 7,0) mas já tem media maior que 5. No módulo __NumPy__ são impementados, via _unfunc_ os operadores lógicos bit a bit do Python, &, |, ^ e ~. Veja a lista a seguir

| Operador	    | _ufunc_             |
|---------------|---------------------|
|``&``          |``np.bitwise_and``   |
|``^``          |``np.bitwise_xor``   |
|&#124;         |``np.bitwise_or``    |
|``~``          |``np.bitwise_not``   |

In [35]:
notasInter = (notas[:, 3] < 7) & (notas[:, 3] > 5)
quantInter = np.count_nonzero(notasInter)
print(quantInter, "notas estão entre 5 e 7")

3 notas estão entre 5 e 7


Repare que foram utilizados parênteses ma expressão. Devido às regras de precedência de operadores, que discutimos no módulo anterior, a expressão geraria um erro. 

Você sabe explica por que? 

## Utilizando mascaras

Os operadores relacionais geram um arrays de booleans. Estes arrays podem ser utilizados como máscaras para extrair subconjuntos de um arrays. 

Por exemplo, se quisermos extrair quais as notas abaixo de 7 na terceira avaliação podemos utilizar uma expressão como a seguinte: 

In [41]:
print(notas[:,2])
x = notas[:,2]
#notas3ra = notas[:, 2] [notas[:, 2] < 7]
notas3ra = x [x < 7]
print(notas3ra)

[7.2 6.7 8.1 7.2 8.1 7.7 7.8 7.9 5.1 5.  5.5 5.1 6.  9.6 6.6 7.5 5.9 4.6
 8.6 9.3 4.6 4.1 4.6 8.  4.8 7.4 6.3 7.7 4.7 9.1]
[6.7 5.1 5.  5.5 5.1 6.  6.6 5.9 4.6 4.6 4.1 4.6 4.8 6.3 4.7]


A expressão anterior retorna um array unidimensional preenchido com todos os valores que atendem à condição posta; em outras palavras, todos os valores nas posições nas quais o array de máscaras é ``True``.

In [42]:
print(x)
print(notas3ra)
notas3ra[0] = 10
print("-------------------")
print(notas3ra)
print(x)

[7.2 6.7 8.1 7.2 8.1 7.7 7.8 7.9 5.1 5.  5.5 5.1 6.  9.6 6.6 7.5 5.9 4.6
 8.6 9.3 4.6 4.1 4.6 8.  4.8 7.4 6.3 7.7 4.7 9.1]
[6.7 5.1 5.  5.5 5.1 6.  6.6 5.9 4.6 4.6 4.1 4.6 4.8 6.3 4.7]
-------------------
[10.   5.1  5.   5.5  5.1  6.   6.6  5.9  4.6  4.6  4.1  4.6  4.8  6.3
  4.7]
[7.2 6.7 8.1 7.2 8.1 7.7 7.8 7.9 5.1 5.  5.5 5.1 6.  9.6 6.6 7.5 5.9 4.6
 8.6 9.3 4.6 4.1 4.6 8.  4.8 7.4 6.3 7.7 4.7 9.1]


Aqui se fz necessário parar para discutir a diferença entre os operadores lógicos ``and`` e ``or`` e os operadores bit a bit ``&`` e ``|``. Em que momento usar um ou outro?

Os operadores lógicos avaliam o objeto como um todo e não cada um dos valores que ele armazena. Já os operadores bit a  bit avaliam a relação entre o contudo dos objetos. 

Quando você usa operadores lógicos, significa que você quer que __Python__ trate o objeto como uma única entidade booleana.

Tem outro recurso de indexação importante que permite utilizar um array de índice como se fosse uma máscara. Esta forma sofisticada de indexação consiste em passar um array de índices para acessar vários elementos do array de uma só vez. 

Suponha que, na turma de alunos um grupo apresentou um trabalho extra, valendo 3 pontos adicionais na última nota. Temos a lista de índices dos alunos que apresentaram o trabalho.

In [43]:
trabalhoExtra = np.array([3, 6, 12, 17, 21, 23, 25, 28])
print(notas[:,2])

[7.2 6.7 8.1 7.2 8.1 7.7 7.8 7.9 5.1 5.  5.5 5.1 6.  9.6 6.6 7.5 5.9 4.6
 8.6 9.3 4.6 4.1 4.6 8.  4.8 7.4 6.3 7.7 4.7 9.1]


In [44]:
print(notas[trabalhoExtra,2])

[7.2 7.8 6.  4.6 4.1 8.  7.4 4.7]


In [45]:
notas[trabalhoExtra,2] += 3
nota3 = notas[:,2]
nota3[nota3 > 10] = 10
print(notas[:,2])

[ 7.2  6.7  8.1 10.   8.1  7.7 10.   7.9  5.1  5.   5.5  5.1  9.   9.6
  6.6  7.5  5.9  7.6  8.6  9.3  4.6  7.1  4.6 10.   4.8 10.   6.3  7.7
  7.7  9.1]


## Ordenação de _ndarrays_ 

Um dos recursos importantes que destacamos na implementação de listas em __Python__ foi a implementação de funções que ordenam a lista, sempre que ela esteja formado por elementos que sejam comparáveis uns com os outros. 

Os _ndarrys_ são formados por tipos numéricos e, em muitos casos, pode ser necessário ordenar os elementos em ordem crescente ou decrescente. 

Você provavelmente já pesquisou algoritmos de ordenação para resolver algumas tarefa, sobre tudo do módulo de Programação Imperativa.  

*insertion sorts*, *selection sorts*, *merge sorts*, *quick sorts*, *bubble sorts*,

Algoritmos como o de __ordenação por inserção (insertion sorts)__, __ordenação por seleção (selection sorts)__, __ordenação por mesclagem (merge sorts)__ , __ordenação quick sorts__, __ordenação da bolha(bubble sorts)__, são tradicionalmente estudados em cursos de estruturas de dados e algoritmos.

O algoritmos de __selection sorts__, por exemplo, procura repetidamente o valor mínimo de uma lista e faz trocas até que a lista seja classificada. 

In [46]:
def selection_sort(x):
    for i in range(len(x) - 1):
        iTroca = i + np.argmin(x[i:])
        (x[i], x[iTroca]) = (x[iTroca], x[i])
    return x

In [47]:
x = np.random.randint(0, 30, 10)
print(x)    
selection_sort(x)
print(x)

[28  9 28 28  3  9 24  4  4 25]
[ 3  4  4  9  9 24 25 28 28 28]


A ordenação por seleção não é dos algoritmos mais eficientes de ordenação, mas não vamos entrar em detalhes sobre complexidade de algoritmos neste curso,  

Felizmente, __Python__ disponibiliza algoritmos de ordenação que são muito mais eficientes. No __NumPy__, por exemplo, temos a função ``sort``

In [48]:
x = np.random.randint(0, 30, 10)
print(x)
# Se se deseja preservar o array original sem ordenar
y = np.sort(x)
print(y)
print(x)
# Já se queremos ordenar o array original
x.sort()
print(x)

[24  0  7  0  2 22  4 18  2 13]
[ 0  0  2  2  4  7 13 18 22 24]
[24  0  7  0  2 22  4 18  2 13]
[ 0  0  2  2  4  7 13 18 22 24]


Uma variação do ``sort`` é o ``argsort``, que retorna um array de índices que, quando usado como máscara, retorna o array ordenado. 

In [49]:
x = np.random.randint(0, 30, 10)
print(x)
iOrd = np.argsort(x)
print(iOrd)
print(x[iOrd])

[21 14 11  4 24 10 14 26  0  4]
[8 3 9 5 2 1 6 0 4 7]
[ 0  4  4 10 11 14 14 21 24 26]


## Tipos de dados estruturados

Como vimos até aqui __NumPy__ fornece uma opção muito eficiente para tratamento dados homogêneos. Entretanto muitas vezes nos deparamos com tipos de dados estruturados, ao estilo dos registros que aprendemos a utilizar em __C/C++__. 

Vamos ver rapidamente como trabalhar como com matrizes formadas por tipos de dados estruturados, ainda que este tema será abordada de forma mais completa no próximo tema deste curso, quando aprenderemos a utilizar os ``DataFrames``de __Pandas__.

Já vimos que, com ajuda de dicionários podemos tratar de diversas categorias de dados que estão relacionados. Imaginem que temos o seguinte caso hipotético. 

In [52]:
alunos = ['nomeAluno01', 'nomeAluno02', 'nomeAluno03', 'nomeAluno04']
matrícula = np.random.randint(0, 1000, 4)
prova_1 = np.random.uniform(0, 10, 4)

Esta forma de tratar dados estruturados resulta em uma organização dos dados um pouco confusa. Não há nada nas expressões anteriores aqui que diga que os três arrays estão relacionados. Seria mais natural se pudéssemos usar uma única estrutura para armazenar todos esses dados. 

Sabemos que poderiamos, por exemplo, criar uma lista de dicionários __Python__. Entretanto __NumPy__ pode lidar com isso por meio de _ndarrays_ estruturados, que são arrays com tipos de dados compostos.

Para isto podemos criar um _ndarray_ estruturado usando uma especificação de tipo de dados composto.

In [53]:
data = np.zeros(4, dtype={'names':('nome', 'nMatricula', 'prova_1'),
                          'formats':('U50', 'i4', 'f4')})
print(data.dtype)

[('nome', '<U50'), ('nMatricula', '<i4'), ('prova_1', '<f4')]


Na definição anterior, ``'U50'`` se traduz em "string Unicode de comprimento máximo 50", ``'i4'`` significa "inteiro com sinal de 4 bytes" e 'f4' se traduz em "ponto flutuante de 4 bytes (4 bytes = 32 bits)".

In [54]:
data['nome'] = alunos
data['nMatricula'] = matrícula
data['prova_1'] = prova_1
print(data)

[('nomeAluno01', 801, 5.2456264 ) ('nomeAluno02',  45, 0.15883586)
 ('nomeAluno03', 512, 8.066707  ) ('nomeAluno04', 566, 6.6620936 )]


Os códigos de formatação abreviados, na forma de uma string, podem parecer confusos, mas seguem algumas regras simples de entender.

* O primeiro caractere (opcional) é ``<`` ou ``>``, que significa "little endian" ou "big endian", respectivamente, e especifica a convenção de ordenação para bits mais significativos.
* O próximo caractere especifica o tipo de dados: caracteres, bytes, inteiros, pontos flutuantes e assim por diante.
* Os últimos caracteres representam o tamanho do objeto em bytes.

| Caractere        | Tipo                  | Exemplo                             |
| ---------        | -----------           | -------                             | 
| ``'b'``          | Byte                  | ``np.dtype('b')``                   |
| ``'i'``          | Inteiro com sinal     | ``np.dtype('i4') == np.int32``      |
| ``'u'``          | Inteiro sem sinal     | ``np.dtype('u1') == np.uint8``      |
| ``'f'``          | Ponto flutuante       | ``np.dtype('f8') == np.int64``      |
| ``'c'``          | Complexo              | ``np.dtype('c16') == np.complex128``|
| ``'S'``, ``'a'`` | String                | ``np.dtype('S5')``                  |
| ``'U'``          | Unicode string        | ``np.dtype('U') == np.str_``        |
| ``'V'``          | Dados não tratados    | ``np.dtype('V') == np.void``        |

__Nota__: Um sistema _big endian_ armazena o _byte_ mais significativo de uma palavra no menor endereço de memória e o _byte_ menos significativo no maior. Um sistema _little endian_, por outro lado, armazena o _byte_ menos significativo no menor endereço. _Big endian_ é a ordem dominante em protocolos de rede, onde é conhecido como ordem de rede, transmitindo primeiro o _byte_ mais significativo. Por outro lado, _little endian_ é a ordem dominante para arquiteturas de processador (__x86__, a maioria das implementações __ARM__, implementações básicas de __RISC-V__) e sua memória associada. Os formatos de arquivo podem usar qualquer ordem; alguns formatos usam uma mistura de ambos ou contêm um indicador de qual ordem é usada em todo o arquivo.

Agora, que o _ndarray_ estruturado foi criado, você pode se referir a valores por índice ou por nome.

In [55]:
# Somente os nomes
print(data['nome'])

['nomeAluno01' 'nomeAluno02' 'nomeAluno03' 'nomeAluno04']


In [56]:
# Apenas um registro
print(data[0])

('nomeAluno01', 801, 5.2456264)


In [57]:
# número de matrícula do último aluno
print(data[-1]['nMatricula'])

566


In [58]:
# Utilizando filtros booleanos
print(data[data['prova_1'] > 5]['nome'])

['nomeAluno01' 'nomeAluno03' 'nomeAluno04']


Analisando um pouco mais como criar este tipo de arrays

In [59]:
# como vimos, podemos utilizar dicionario
tipo = np.dtype({'names':('nome', 'nMatricula', 'prova_1'),
                 'formats':('U50', 'i4', 'f4')})
print(tipo)

[('nome', '<U50'), ('nMatricula', '<i4'), ('prova_1', '<f4')]


In [60]:
# se ficar confuso, podemos utilizar os tipos de dados nativos
tipo = np.dtype({'names':('nome', 'nMatricula', 'prova_1'),
                 'formats':((np.str_, 50), 'int32', np.float32)})
print(tipo)

[('nome', '<U50'), ('nMatricula', '<i4'), ('prova_1', '<f4')]


In [61]:
# podemos utilizar ainda uma lista de tuplas
tipo = np.dtype([('nome', 'U50'), ('nMatricula', 'i4'), ('prova_1', 'f4')])
print(tipo)

[('nome', '<U50'), ('nMatricula', '<i4'), ('prova_1', '<f4')]


In [62]:
# se não for importante o nome dos campos, podemos utilizar uma string apenas com os tipos
tipo = np.dtype('U50, i4, f4')
print(tipo)

[('f0', '<U50'), ('f1', '<i4'), ('f2', '<f4')]


__NumPy__ possui ainda a classe ``np.recarray``, que é quase idêntica aos arrays estruturados que acabamos de descrever, mas com um recurso adicional: os campos podem ser acessados como atributos em vez de chaves de dicionário

In [63]:
data['nome']

array(['nomeAluno01', 'nomeAluno02', 'nomeAluno03', 'nomeAluno04'],
      dtype='<U50')

Se visualizarmos nossos dados como uma matriz de registros, poderemos acessar estes dados de forma mais simples

In [65]:
data_ = data.view(np.recarray)
data_.nome
print(data_[0].nome)

nomeAluno01


A desvantagem é que, para matrizes de registros, há alguma sobrecarga extra envolvida no acesso aos campos, mesmo quando se usa a mesma sintaxe.

In [66]:
%timeit data['nome']
%timeit data_['nome']
%timeit data_.nome

81.5 ns ± 0.809 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
1.18 µs ± 7.56 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2 µs ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
